#!/usr/bin/sh

ln -fs $(pwd)/bashrc ~/.bashrc
ln -fs $(pwd)/gitconfig ~/.gitconfig
ln -fs $(pwd)/screenrc ~/.screenrc

if [ -n "$OS" ] && [ "$OS" = "Windows_NT" ]
then
    ln -fs $(pwd)/minttyrc ~/.minttyrc
    ln -fs $(pwd)/startxwinrc ~/.startxwinrc
    ln -fs $(pwd)/XWinrc ~/.XWinrc
fi

cd emacs; ./setup; cd ..
cd fonts; ./setup; cd ..
