#!/bin/bash

# Add font path.
if [ -x xset ]
then
    xset +fp ~/.fonts
fi

# Programs to load with X-Server.
#[ -x /usr/bin/emacs ] && /usr/bin/emacs
[ -x /usr/bin/fbpanel ] && exec /usr/bin/fbpanel -p multiwindow
